name: demo
on:
  push:
   branches:
     - master

   runs-on: ubuntu-latest

   steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: build and push Docker image
      env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

   run: |
      docker buildx build \
        --platform linux/amd64 \
        --push \
        --tag $USERNAME/my-demo:v0.2
